baseURL = "https://lecdency-l.github.io/"
relativeURLs = false
canonifyURLs = true
languageCode = 'en-us'
title = "Lecdency's Blog"
theme = "PaperMod"

[params]
ShowToc = true
TocOpen = true
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowWordCount = true
  [params.assets]
  disableFingerprinting = true

# 启用搜索
[outputs]
home = ["HTML", "RSS", "JSON"]

[menu]

[[menu.main]]
name = "归档"
url = "/archives/"
weight = 1

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 2

[[menu.main]]
name = "搜索"
url = "/search/"
weight = 3


[taxonomies]
  tag = "tags"
